# Node Exporter web configuration
# Cấu hình để giảm thiểu lỗi connection reset
http_server_config:
  http2: false
  max_requests: 5
  max_connections: 10
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
